import {initReports} from './reports.mjs';
import {COINS,MARKET_COINS,signalHistory,manualCost,DAY,finite,sma,indicators,normalizeKlines,analyze,emptyAccount,validateAccount,portfolio,applyTrade,backtest,quantityFromInput,intradaySignal} from './engine.mjs';
import {Chart,spark} from './charts.mjs';
const sandbox=new URLSearchParams(location.search).has('sandbox');
const $=id=>document.getElementById(id),KEY=sandbox?'jace.crypto.sandbox.v1':'jace.crypto.account.v1',CACHE='jace.crypto.market.v1';
const fmt=(v,d=2)=>finite(v)?new Intl.NumberFormat('en-US',{maximumFractionDigits:d,minimumFractionDigits:d}).format(v):'—';
const money=v=>finite(v)?'$'+fmt(v):'—';
const pct=v=>finite(v)?(v>0?'+':'')+fmt(v*100,2)+'%':'—';
const cls=v=>finite(v)?v>=0?'positive':'negative':'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=t=>new Date(t).toLocaleDateString('ko-KR',{timeZone:'UTC',year:'numeric',month:'2-digit',day:'2-digit'});
let account=emptyAccount(),storageIssue=false;try{const raw=localStorage.getItem(KEY);if(raw)account=validateAccount(JSON.parse(raw));}catch{storageIssue=true;}
const state={allocation:'target',currency:'KRW',fx:null,coin:'BTC',days:180,candles:false,bands:false,markets:{},prices:{},tickers:{},analyses:{},updated:{},tickerUpdated:{},busy:false,ws:null,wsOpen:false,retry:0,global:null,fng:null,cached:false,lastRender:0};
const won=v=>finite(v)?'₩'+fmt(v,0):'—';
function rate(){return account.fx>0?account.fx:state.fx?.rate||0;}
function fxFresh(){return account.fx>0||!!state.fx&&Date.now()-state.fx.t<120000;}
function display(v){return state.currency==='KRW'?(finite(v)&&rate()>0?won(v*rate()):'—'):money(v);}
function renderFX(){$('fx-status').innerHTML=rate()>0?`1 USDT <strong>= ${won(rate())}</strong><small>${account.fx>0?'직접 입력 환산 가격':`업비트 KRW-USDT · ${new Date(state.fx.t).toLocaleTimeString('ko-KR')} ${fxFresh()?'갱신':'지연'}`}</small>`:'USDT / KRW 환산 가격 연결 대기';}
async function loadFX(){try{const rows=await json('https://api.upbit.com/v1/ticker?markets=KRW-USDT');const f=rows?.[0];if(f&&finite(+f.trade_price)&&+f.trade_price>0)state.fx={rate:+f.trade_price,t:+f.timestamp||Date.now()};}catch{}}
function connectFX(){if(connectFX.socket&&[0,1].includes(connectFX.socket.readyState))return;const ws=new WebSocket('wss://api.upbit.com/websocket/v1');connectFX.socket=ws;ws.onopen=()=>ws.send(JSON.stringify([{ticket:'jace-fx'},{type:'ticker',codes:['KRW-USDT']}]));ws.onmessage=async e=>{try{const d=JSON.parse(typeof e.data==='string'?e.data:await e.data.text());if(d.code==='KRW-USDT'&&d.trade_price>0){state.fx={rate:+d.trade_price,t:+d.timestamp||Date.now()};if(Date.now()-state.lastRender>1800)render();}}catch{}};ws.onerror=()=>ws.close();ws.onclose=()=>{clearTimeout(connectFX.timer);connectFX.timer=setTimeout(connectFX,30000);};}
$('currency-tabs').onclick=e=>{const b=e.target.closest('[data-currency]');if(!b)return;state.currency=b.dataset.currency;for(const x of e.currentTarget.children)x.classList.toggle('active',x===b);render();};
let saveError='';function persist(a){try{localStorage.setItem(KEY,JSON.stringify(a));account=a;saveError='';window.dispatchEvent(new Event('jace-account-change'));return true;}catch{saveError='브라우저 저장 공간에 저장하지 못했습니다. 백업을 내보내세요.';return false;}}
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4500);}
const priceChart=new Chart($('price-chart'),$('price-tooltip')),perfChart=new Chart($('performance-chart'));
function recompute(){for(const c of MARKET_COINS)state.analyses[c.id]=analyze(state.markets[c.id]||[],c.period);}
function freshness(id){return Date.now()-(state.tickerUpdated[id]||0)<120000;}
function allFresh(){return COINS.every(c=>freshness(c.id));}
function visiblePrice(id){return state.prices[id];}
function renderStatus(){const fresh=MARKET_COINS.filter(c=>freshness(c.id)).length;const live=state.wsOpen&&fresh===MARKET_COINS.length;$('connection').textContent=live?'LIVE':fresh===MARKET_COINS.length?'시세 연결됨':fresh?`${fresh}/${MARKET_COINS.length} 시세 연결`:'시세 확인 중';$('connection').className='connection'+(live?' live':'');$('local-clock').textContent=new Date().toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Seoul'})+' KST';const stale=MARKET_COINS.filter(c=>state.analyses[c.id]?.stale).map(c=>c.id);const missing=MARKET_COINS.filter(c=>!state.analyses[c.id]).map(c=>c.id);let msg=fresh===MARKET_COINS.length?'실시간 시세 연결 · 잔고는 이 브라우저에 저장 · 확정 신호와 장중 움직임을 구분해 표시합니다.':'시세 연결을 확인하고 있습니다. 저장된 값이 있으면 마지막 수신값을 표시하며, 30초마다 다시 시도합니다.';if(stale.length)msg+=` 일봉 지연: ${stale.join(', ')}. 최신 확정 신호로 사용하지 마세요.`;if(missing.length&&!state.busy)msg+=` 일봉 수신 실패: ${missing.join(', ')}. 새로고침으로 재시도할 수 있습니다.`;if(storageIssue)msg+=' 기존 저장 데이터를 읽지 못했습니다. 원본은 유지되며 백업으로 복원할 수 있습니다.';if(saveError)msg+=' '+saveError;if(!rate())msg+=' 원화 환산 가격을 받지 못해 원화 합산을 보류합니다.';else if(!fxFresh())msg+=' 환산 가격 지연: 마지막 수신값 기준입니다.';if(sandbox)msg='연습 모드 · 실제 잔고와 별도로 저장합니다. '+msg;$('data-notice').textContent=msg;$('data-notice').className='notice'+(fresh<MARKET_COINS.length||stale.length||missing.length||storageIssue||saveError||!fxFresh()?' error':'');}
function renderSummary(){const p=portfolio(account,state.prices,rate()),isSet=p.cost>0||account.cash>0||account.cashKRW>0||p.rows.some(r=>r.qty>0),fresh=allFresh(),above=COINS.filter(c=>state.analyses[c.id]?.above&&!state.analyses[c.id]?.stale).length;const wonMode=state.currency==='KRW',gain=wonMode?p.pnlKRW:p.pnl,basis=wonMode?p.costKRW:p.cost;const data=[['총 자산 · 원화 통합',isSet?won(p.valueKRW):'잔고를 입력하세요',isSet?`${fmt(p.value)} USDT 상당 · 현금 + USDT + 코인`:'원화 현금 · USDT · 코인을 한곳에','◉'],['미실현 평가손익',isSet&&basis>0?(wonMode?won(gain):money(gain)):'—',basis>0?`${pct(finite(gain)?gain/basis:null)} · ${wonMode?'원화':'USDT'} 매입원가 대비`:'평균 매입가 입력 후 계산','↗'],['현금 + USDT',isSet?(rate()?won((account.cashKRW||0)+account.cash*rate()):'환산 대기'):'—',`현금 ${won(account.cashKRW||0)} + ${fmt(account.cash)} USDT`,'◷'],['전략선 위의 종목',`${above}<small>/ 4 종목</small>`,'마지막 확정 종가 기준 · 지연 종목 제외','⌁']];$('stats').innerHTML=data.map((d,i)=>`<article class="stat"><div class="stat-top">${d[0]}<span class="stat-symbol">${d[3]}</span></div><div class="stat-value ${i===1?cls(gain):''}" ${!isSet&&i===0?'style="font-size:20px"':''}>${d[1]}</div><div class="stat-sub">${esc(d[2])}</div></article>`).join('');}

function renderCoins(){ $('coin-cards').innerHTML=MARKET_COINS.map(c=>{const t=state.tickers[c.id],a=state.analyses[c.id],cl=(state.markets[c.id]||[]).slice(-35).map(b=>b.c);return `<button class="coin-card ${state.coin===c.id?'selected':''} ${c.reference?'reference-card':''}" data-coin="${c.id}"><div class="coin-card-top"><span class="coin-icon" style="--coin:${c.color}">${c.mark}</span><span class="coin-name">${c.en}<small>${c.id} / USDT</small></span><span class="target ${c.reference?'reference-tag':''}">${c.reference?'참고 전용':c.weight*100+'%'}</span></div><div class="coin-card-price">${display(visiblePrice(c.id))}</div><div class="coin-card-bottom"><span class="${cls(t?.change)}">${pct(t?.change)} <span class="muted">24h${freshness(c.id)?'':' · 지연'}</span></span>${spark(cl,c.color)}</div></button>`;}).join('');$('coin-tabs').innerHTML=MARKET_COINS.map(c=>`<button data-coin="${c.id}" class="${state.coin===c.id?'active':''}">${c.id}${c.reference?'<small>참고</small>':''}</button>`).join('');}
function renderChart(){const c=MARKET_COINS.find(x=>x.id===state.coin),all=(state.markets[c.id]||[]).map(b=>b.t<=Date.now()&&b.end>=Date.now()&&finite(state.prices[c.id])?{...b,c:state.prices[c.id],h:Math.max(b.h,state.prices[c.id]),l:Math.min(b.l,state.prices[c.id])}:b),a=state.analyses[c.id],t=state.tickers[c.id],ind=indicators(all,c.period),len=Math.min(state.days,all.length),bars=all.slice(-len);$('chart-price').innerHTML=`<span class="coin-icon" style="--coin:${c.color}">${c.mark}</span><strong>${display(visiblePrice(c.id))}</strong><small>${state.currency==='KRW'?'KRW 환산':'USDT'}</small><span class="change ${cls(t?.change)}">${pct(t?.change)}</span>`;$('chart-empty').hidden=bars.length>1;if(state.currency==='KRW'&&!rate()){$('chart-empty').hidden=false;$('chart-empty').textContent='원화 환산 가격 수신 대기 · USDT 표시로 확인할 수 있습니다.';}if(!bars.length)$('chart-empty').textContent=state.busy?'시세를 불러오고 있습니다.':'시세 연결이 필요합니다. 상단 새로고침으로 다시 시도하세요.';const mult=state.currency==='KRW'?rate():1,scale=v=>finite(v)&&mult>0?v*mult:null,history=signalHistory(all,c.period),live=intradaySignal(a,c.period,state.prices[c.id]),active=all.find(b=>b.t<=Date.now()&&b.end>=Date.now());const markers=history.filter(e=>bars.some(b=>b.t===e.t));if(active&&live&&freshness(c.id)&&!a?.stale&&['up','down'].includes(live.cross))markers.push({t:active.t,type:live.cross,price:state.prices[c.id],confirmed:false});priceChart.set({bars:mult>0?bars.map(b=>({...b,o:b.o*mult,h:b.h*mult,l:b.l*mult,c:b.c*mult})):[],markers:markers.map(e=>({...e,price:e.price*mult})),candles:state.candles,volume:true,color:'#d2f99a',lines:[{values:ind.ma.slice(-len).map(scale),color:'#e9b762',label:`SMA ${c.period}`},{values:ind.ma50.slice(-len).map(scale),color:'#859acf',dash:[4,3],label:'SMA 50'}],band:state.bands?{upper:ind.upper.slice(-len).map(scale),lower:ind.lower.slice(-len).map(scale)}:null});$('chart-legend').innerHTML=`<span><i style="background:var(--accent)"></i>${c.id} 가격</span><span><i style="background:#e9b762"></i>전략 SMA ${c.period}</span><span><i style="background:#859acf"></i>SMA 50</span><span class="positive">▲ B 매수 확정</span><span class="negative">▼ S 매도 확정</span><span>점선 B? / S? 장중 예고</span>`;$('indicator-strip').innerHTML=[['RSI (14)',fmt(a?.rsi,1),a?a.rsi>70?'과매수 구간':a.rsi<30?'과매도 구간':'중립 구간':'확정 일봉 대기'],['MACD 히스토그램 · USDT',fmt(a?.hist,2),a?a.hist>=0?'시그널 위':'시그널 아래':'—'],['ATR (14)',a?fmt(a.atr/a.close*100,2)+'%':'—','종가 대비 변동폭'],['거래량 / 20일',a?fmt(a.volumeRatio,2)+'×':'—','직전 20일 평균 대비']].map(d=>`<div><small>${d[0]}</small><strong>${d[1]}</strong><span>${d[2]}</span></div>`).join('');$('candle-date').textContent=a?`최근 확정 ${date(a.closed.at(-1).t)}`:'';renderChartSignals(c,a,live,history,markers);}
function renderChartSignals(c,a,live,history,markers){
 const valid=!!a&&!a.stale,liveValid=valid&&freshness(c.id),last=history.at(-1),crossLabel=type=>type==='up'?'매수':type==='down'?'매도':'교차 없음';
 $('chart-signal-summary').innerHTML=`<div><small>직전 마감 확정</small><strong class="${a?.cross==='up'?'positive':a?.cross==='down'?'negative':''}">${valid?crossLabel(a.cross):'데이터 확인 중'}</strong><span>${a?date(a.closed.at(-1).t):'—'}</span></div><div><small>실시간 예고 · 미확정</small><strong class="${live?.cross==='up'?'positive':live?.cross==='down'?'negative':''}">${liveValid?crossLabel(live?.cross):'시세 확인 중'}</strong><span>${liveValid?'돌파 기준 '+display(live?.threshold):'신선한 시세 수신 후 판정'}</span></div><div><small>최근 확정 신호</small><strong class="${last?.type==='up'?'positive':last?.type==='down'?'negative':''}">${last?crossLabel(last.type):'관측 구간 내 없음'}</strong><span>${last?date(last.t):'—'}</span></div>`;
 const shown=markers.filter(e=>e.confirmed),recent=shown.slice(-4).reverse();
 $('chart-signal-history').innerHTML=`<div class="signal-history-head"><span>${c.id} · 표시 구간 매수 ${shown.filter(e=>e.type==='up').length}회 / 매도 ${shown.filter(e=>e.type==='down').length}회</span>${c.reference?'<span class="reference-tag">XRP 참고 전용 · 포트폴리오 제외</span>':''}</div><div class="signal-events">${recent.length?recent.map(e=>`<span class="signal-event ${e.type==='up'?'positive':'negative'}"><b>${e.type==='up'?'▲ B 매수':'▼ S 매도'}</b><time>${date(e.t)}</time><span>${display(e.price)}</span></span>`).join(''):'<span class="muted">이 구간에는 확정 돌파가 없습니다. 차트 기간을 늘려 이전 신호를 확인하세요.</span>'}</div><p>${c.reference?'XRP는 기존 검증·최근 5년 연구의 235일 SMA를 참고 기준으로 관찰합니다. ':''}B/S는 종가에서 확정된 신호이며 실제 체결 기록이 아닙니다. 전략 체결 기준은 다음 일봉 시가입니다.</p>`;
 $('price-chart').setAttribute('aria-label',`${c.id} 가격과 ${c.period}일 이동평균 차트. 확정 매수 ${shown.filter(e=>e.type==='up').length}회, 확정 매도 ${shown.filter(e=>e.type==='down').length}회. B는 매수, S는 매도, 물음표 표식은 미확정 장중 예고.`);
}
function renderAllocation(){const p=portfolio(account,state.prices,rate()),actual=state.allocation==='actual',length=2*Math.PI*91;let offset=0;const data=actual?COINS.map(c=>({...c,weight:p.value>0?(p.rows.find(r=>r.id===c.id).value||0)/p.value:0})).concat([{id:'KRW',name:'원화 현금',color:'#728f73',weight:p.valueKRW>0?(account.cashKRW||0)/p.valueKRW:0},{id:'USDT',name:'테더 현금',color:'#55b8a0',weight:p.value>0?account.cash/p.value:0}]):COINS;$('donut-segments').innerHTML=data.map(c=>{const gap=Math.min(4,c.weight*length*.12),s=`<circle cx="120" cy="120" r="91" fill="none" stroke="${c.color}" stroke-width="20" stroke-dasharray="${Math.max(0,c.weight*length-gap)} ${length-c.weight*length+gap}" stroke-dashoffset="${-offset}"/>`;offset+=c.weight*length;return s;}).join('');const core=actual?data[0].weight+data[1].weight:.85;$('donut-center').innerHTML=`<small>${actual?'CURRENT ALLOCATION':'CORE ALLOCATION'}</small><strong>${actual&&!(p.value>0)?'—':fmt(core*100,actual?1:0)}<span>%</span></strong><span>${actual&&!(p.value>0)?'잔고 입력 후 표시':'BTC + ETH'}</span>`;$('allocation-list').innerHTML=data.map(c=>`<div class="allocation-row"><span class="dot" style="background:${c.color}"></span><span>${c.id}</span><small>${c.name}</small><strong>${fmt(c.weight*100,actual?1:c.weight===.075?1:0)}%</strong><span class="bar"><i style="background:${c.color};width:${c.weight*100}%"></i></span></div>`).join('');}
$('allocation-mode').onclick=e=>{const b=e.target.closest('[data-allocation]');if(!b)return;state.allocation=b.dataset.allocation;for(const x of e.currentTarget.children)x.classList.toggle('active',x===b);renderAllocation();};

function renderSignals(){let signals=0;$('signals-body').innerHTML=MARKET_COINS.map(c=>{const a=state.analyses[c.id],p=visiblePrice(c.id);if(!a)return `<tr><td>${c.id}</td><td>${c.period}일 SMA</td><td colspan="5" class="muted">확정 일봉 데이터가 필요합니다.</td></tr>`;if(!a.stale&&['up','down'].includes(a.cross))signals++;const live=intradaySignal(a,c.period,p),today=live?.ma,dist=live?.distance,holding=(account.holdings[c.id]?.qty||0)>0,liveOK=freshness(c.id)&&!a.stale;const labels={up:'↗ 매수 신호 확정',down:'↘ 매도 신호 확정',none:c.reference?(a.above?'상단 · 참고 관찰':'하단 · 참고 관찰'):a.above?(holding?'보유 유지':'신규 돌파 대기'):(holding?'하단 · 보유 점검':'현금 대기'),unknown:'판정 대기'};return `<tr><td><div class="table-coin"><span class="coin-icon" style="--coin:${c.color}">${c.mark}</span><div>${c.id}<small>${c.reference?'참고 전용 · 비중 제외':'목표 '+c.weight*100+'%'}</small></div></div></td><td>${c.period}일 <span class="muted">SMA</span><span class="secondary-line">${display(a.ma)} · 확정</span></td><td>${display(p)}<span class="secondary-line ${cls(dist)}">${finite(dist)?pct(dist)+' · 장중 SMA 대비':'장중 일봉 수신 대기'}</span></td><td><span class="badge ${a.stale?'warn':a.cross==='down'?'down':a.cross==='up'?'':'neutral'}">${a.stale?'일봉 지연':labels[a.cross]}</span><span class="secondary-line">${date(a.closed.at(-1).t)}</span></td><td><span class="badge ${!liveOK?'warn':live?.cross==='down'?'down':live?.cross==='up'?'':'neutral'}">${!liveOK?'시세 확인 필요':live?.cross==='up'?'↗ 매수 예고':live?.cross==='down'?'↘ 매도 예고':c.reference?'교차 없음 · 참고':holding?(dist>=0?'보유 유지':'하단 · 점검'):'신규 돌파 대기'}</span><span class="secondary-line">${liveOK?'미확정 · 기준 '+display(live?.threshold):'실시간 판정 보류'}</span></td><td>${fmt(a.rsi,1)}<span class="rsi-bar"><i style="width:${a.rsi}%"></i></span></td><td>${a.recent?date(a.recent.date):'—'}<span class="secondary-line">${a.recent?a.recent.type==='up'?'상향 돌파':'하향 돌파':'관측 구간 내 없음'}</span></td></tr>`;}).join('');$('signal-count').textContent=String(signals);}
function renderHoldings(){const p=portfolio(account,state.prices,rate()),krw=state.currency==='KRW';$('holdings-body').innerHTML=p.rows.map(r=>{const gain=krw?r.pnlKRW:r.pnl,ret=krw?r.returnKRW:r.return,cost=krw?r.costKRW:r.cost;return `<tr><td><div class="table-coin"><span class="coin-icon" style="--coin:${r.color}">${r.mark}</span><div>${r.id}<small>${r.name}</small></div></div></td><td>${fmt(r.qty,Math.min(8,r.id==='BTC'?8:6))}</td><td>${r.avg>0?(krw&&r.avgKRW>0?won(r.avgKRW):display(r.avg)):'미입력'}<span class="secondary-line">${krw&&r.avgKRW>0?'원화 매입원가':krw?'USDT 원가 현재 환산':'USDT 매입원가'}</span></td><td>${display(r.price)}</td><td>${r.avg>0?(krw?won(cost):money(cost)):'—'}</td><td>${display(r.value)}</td><td class="${cls(gain)}">${r.qty?(krw?won(gain):money(gain)):'—'}</td><td class="${cls(ret)}">${pct(ret)}</td><td>${finite(r.actual)?fmt(r.actual*100,1)+'%':'—'} <span class="muted">/ ${r.weight*100}%</span></td><td>${finite(r.delta)&&p.value>0?(r.delta>0?'+':'')+display(r.delta):'—'}<span class="secondary-line">비중 참고값</span></td></tr>`;}).join('');$('balance-foot').textContent=`원화 현금 ${won(account.cashKRW||0)} + USDT ${fmt(account.cash,2)} · ${account.updatedAt?'잔고 수정 '+new Date(account.updatedAt).toLocaleString('ko-KR'):'아직 잔고를 입력하지 않았습니다.'} · 원화 매입가를 입력하면 원화 원가로 손익을 계산합니다. 원화 원가 미입력 종목은 USDT 원가를 현재 환산합니다. 평가손익은 현재 보유분의 미실현 손익입니다.${allFresh()?'':' 마지막 수신 시세가 사용될 수 있습니다.'}`;}

function renderContext(){const a=state.analyses.BTC,bars=a?.closed||[],recent=bars.slice(-365),draw=recent.length?recent.at(-1).c/Math.max(...recent.map(b=>b.h))-1:null;const f=state.fng;const fFresh=f&&Date.now()-f.t<2*DAY;const eth=state.prices.ETH,btc=state.prices.BTC;$('context-cards').innerHTML=`<article class="context-card"><div><small>공포 · 탐욕 지수</small><span class="eyebrow">MARKET SENTIMENT</span></div><div><strong>${fFresh?f.value:'—'} <small>/ 100</small></strong><span>${fFresh?(f.value<25?'극도의 공포':f.value<45?'공포':f.value<55?'중립':f.value<75?'탐욕':'극도의 탐욕'):'수신 대기'}</span></div><div class="meter">${fFresh?`<i style="left:${Math.min(f.value,99)}%"></i>`:''}</div><p>Alternative.me · ${fFresh?date(f.t)+' · 일 1회':'외부 지수 연결 시 표시'}</p></article><article class="context-card"><div><small>BTC 고점 대비 하락폭</small><span class="eyebrow">DRAWDOWN</span></div><div><strong class="${cls(draw)}">${pct(draw)}</strong><span class="muted">${Math.min(365,recent.length)}일 기준</span></div><p>관측기간 장중 최고가 대비 최근 확정 종가<br>${a?date(a.closed.at(-1).t)+' 기준':'—'}</p></article><article class="context-card"><div><small>ETH / BTC 상대 강도</small><span class="eyebrow">RELATIVE VALUE</span></div><div><strong>${btc&&eth?fmt(eth/btc,5):'—'}</strong><span class="muted">BTC</span></div><p>ETH 가격 ÷ BTC 가격 · ${allFresh()?'최신 시세':'마지막 수신 시세'}<br>상승하면 이더리움의 상대적 강세</p></article>`;}
let perfKey='';function renderPerformance(force=false){const key=COINS.map(c=>(state.markets[c.id]||[]).length+':'+state.analyses[c.id]?.closedAt).join('|')+'|'+$('performance-range').value;if(!force&&key===perfKey)return;perfKey=key;const r=backtest(state.markets,+$('performance-range').value);if(!r){$('perf-stats').innerHTML='<small class="muted">네 종목의 충분한 일봉 데이터가 수신되면 계산됩니다.</small>';perfChart.set({bars:[]});return;}$('perf-stats').innerHTML=[['누적 수익률',pct(r.return),cls(r.return)],['연환산 수익률',pct(r.cagr),cls(r.cagr)],['최대 낙폭',pct(r.mdd),'negative'],['매매 횟수',String(r.trades),'']].map(d=>`<div><small>${d[0]}</small><strong class="${d[2]}">${d[1]}</strong></div>`).join('');perfChart.set({bars:r.points.map(p=>({...p,c:p.c*100})),color:'#d2f99a',lines:[{values:r.benchmark.map(p=>p.c*100),color:'#728395',dash:[5,3]}]});$('performance-foot').textContent=`시뮬레이션 · ${date(r.from)}–${date(r.end)} · 시작 100 · BTC 65 / ETH 20 / BNB 7.5 / SOL 7.5 · 종목별 신규 돌파를 기다린 후 다음 시가 체결 · 편도 수수료 0.05% + 슬리피지 0.05% · 마지막 종가 청산. 단순 보유에도 동일 비용 적용. 실제 계좌 수익률이 아니며 과거 성과는 미래 수익을 보장하지 않습니다.`;}
function renderJournal(){if(!account.journal.length){$('journal-content').innerHTML='<div class="empty-state"><strong>기록이 쌓이면, 나만의 투자 기준이 됩니다.</strong>체결한 거래와 투자 메모를 추가해 보세요. 수량과 현금 잔고에도 반영됩니다.</div>';return;}$('journal-content').innerHTML=`<div class="table-scroll"><table><thead><tr><th>체결 일시</th><th>종목</th><th>구분</th><th>수량</th><th>체결가 / 통화</th><th>수수료</th><th>투자 메모</th></tr></thead><tbody>${account.journal.slice(0,100).map(j=>`<tr><td>${esc(new Date(j.date).toLocaleString('ko-KR'))}</td><td>${esc(j.coin)}</td><td><span class="badge ${j.side==='sell'?'down':''}">${j.side==='buy'?'매수':'매도'}</span></td><td>${fmt(j.qty,8)}</td><td>${j.currency==='KRW'?won(j.price):money(j.price)}<span class="secondary-line">${j.currency||'USDT'}</span></td><td>${j.currency==='KRW'?won(j.fee):money(j.fee)}</td><td class="journal-note">${esc(j.note||'—')}</td></tr>`).join('')}</tbody></table></div>${account.journal.length>100?'<div class="panel-foot">최근 100건 표시 · 전체 기록은 백업에 포함됩니다.</div>':''}`;}
function render(){renderStatus();renderFX();renderSummary();renderCoins();renderChart();renderSignals();renderAllocation();renderHoldings();renderContext();renderPerformance();state.lastRender=Date.now();}
async function json(url){const r=await fetch(url,{signal:AbortSignal.timeout(14000),cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json();}
const BASE='https://data-api.binance.vision/api/v3';
async function loadMarket(){if(state.busy)return;state.busy=true;$('refresh').disabled=true;await Promise.allSettled(MARKET_COINS.map(async c=>{const rows=await json(`${BASE}/klines?symbol=${c.id}USDT&interval=1d&limit=1000`);const bars=normalizeKlines(rows);if(bars.length<c.period+2)throw Error('불충분한 캔들');state.markets[c.id]=bars;state.updated[c.id]=Date.now();}));await Promise.allSettled([loadTickers(),loadFX()]);state.busy=false;$('refresh').disabled=false;recompute();render();try{localStorage.setItem(CACHE,JSON.stringify({markets:state.markets,updated:state.updated,prices:state.prices,tickers:state.tickers,tickerUpdated:state.tickerUpdated,fx:state.fx}));}catch{} }
async function loadTickers(){try{const rows=await json(`${BASE}/ticker/24hr?symbols=${encodeURIComponent(JSON.stringify(MARKET_COINS.map(c=>c.id+'USDT')))}`);if(!Array.isArray(rows))throw Error();for(const c of MARKET_COINS){const t=rows.find(x=>x.symbol===c.id+'USDT');if(t&&finite(+t.lastPrice)&&+t.lastPrice>0){state.prices[c.id]=+t.lastPrice;state.tickers[c.id]={change:+t.priceChangePercent/100,volume:+t.quoteVolume};state.tickerUpdated[c.id]=+t.closeTime||Date.now();}}}catch{} }
function connect(){if(state.ws&&[0,1].includes(state.ws.readyState))return;const streams=MARKET_COINS.flatMap(c=>[c.id.toLowerCase()+'usdt@ticker',c.id.toLowerCase()+'usdt@kline_1d']).join('/');const ws=new WebSocket('wss://data-stream.binance.vision/stream?streams='+streams);state.ws=ws;ws.onopen=()=>{state.wsOpen=true;state.retry=0;renderStatus();};ws.onmessage=e=>{try{const d=JSON.parse(e.data).data,id=d?.s?.replace('USDT','');if(!MARKET_COINS.some(c=>c.id===id))return;if(d.e==='24hrTicker'&&+d.c>0){state.prices[id]=+d.c;state.tickers[id]={change:+d.P/100,volume:+d.q};state.tickerUpdated[id]=+d.E;}if(d.e==='kline'&&state.markets[id]){const k=d.k,b={t:+k.t,o:+k.o,h:+k.h,l:+k.l,c:+k.c,v:+k.v,end:+k.T},arr=state.markets[id];if(Object.values(b).every(finite)&&b.c>0){if(arr.at(-1)?.t===b.t)arr[arr.length-1]=b;else if(b.t===arr.at(-1)?.t+DAY)arr.push(b);if(arr.length>1000)arr.shift();}}if(Date.now()-state.lastRender>1800){recompute();render();}}catch{}};ws.onerror=()=>ws.close();ws.onclose=()=>{state.wsOpen=false;renderStatus();clearTimeout(connect.timer);connect.timer=setTimeout(connect,Math.min(60000,2000*2**Math.min(state.retry++,5)));};}
async function sentiment(){try{const d=await json('https://api.alternative.me/fng/?limit=1');const f=d.data?.[0];if(f&&Number.isFinite(+f.value)&&+f.value>=0&&+f.value<=100)state.fng={value:+f.value,t:+f.timestamp*1000};}catch{}renderContext();}
function openBalance(){ $('balance-inputs').innerHTML=COINS.map(c=>`<div class="balance-coin"><div class="balance-coin-title"><span class="coin-icon" style="--coin:${c.color}">${c.mark}</span><strong>${c.id}</strong><span>${display(state.prices[c.id])}</span></div><div class="balance-fields"><label>입력 방식<select name="${c.id}-mode"><option value="qty">코인 수량</option><option value="KRW">원화 평가금액</option><option value="USDT">USDT 평가금액</option></select></label><label>잔고 / 금액<input type="number" name="${c.id}-qty" min="0" step="any" value="${account.holdings[c.id].qty}" required></label><label>매입가 통화<select name="${c.id}-avgCurrency"><option value="USDT" ${account.holdings[c.id].avgKRW>0?'':'selected'}>USDT</option><option value="KRW" ${account.holdings[c.id].avgKRW>0?'selected':''}>KRW 원화</option></select></label><label>1코인 평균 매입가<input type="number" name="${c.id}-avg" min="0" step="any" value="${account.holdings[c.id].avgKRW>0?account.holdings[c.id].avgKRW:account.holdings[c.id].avg}" placeholder="0 = 미입력" required></label></div><p class="input-hint" id="${c.id}-hint"></p></div>`).join('');$('balance-form').elements.cash.value=account.cash;$('balance-form').elements.cashKRW.value=account.cashKRW||0;$('balance-form').elements.fx.value=account.fx;$('balance-error').textContent='';balancePreview();$('balance-dialog').showModal();}
function balancePreview(){const f=new FormData($('balance-form')),fx=+f.get('fx')||state.fx?.rate||0;let coinValue=0,ok=true;for(const c of COINS){try{const amount=+f.get(c.id+'-qty'),mode=f.get(c.id+'-mode'),q=quantityFromInput(amount,mode,state.prices[c.id],fx);if(q>0&&!finite(state.prices[c.id]))throw Error('시세 수신 대기');coinValue+=q*(state.prices[c.id]||0);$(c.id+'-hint').textContent=`${fmt(q,8)} ${c.id} · ${fx>0?won(q*(state.prices[c.id]||0)*fx):'환산 대기'}`;}catch(err){ok=false;$(c.id+'-hint').textContent=err.message;}}$('balance-conversion').textContent=ok&&fx>0?`합산 미리보기 ${won(+f.get('cashKRW')+(+f.get('cash')+coinValue)*fx)} · 1 USDT = ${won(fx)} · 금액 입력은 저장 시 수량으로 확정`:'환산 가격과 코인 시세 수신 후 합산할 수 있습니다.';}

$('edit-balance').onclick=openBalance;
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>b.closest('dialog').close();
$('balance-form').oninput=balancePreview;$('balance-form').onchange=balancePreview;
$('balance-form').onsubmit=e=>{e.preventDefault();try{const form=new FormData(e.target),a=structuredClone(account),fx=+form.get('fx')||state.fx?.rate||0;for(const c of COINS){const mode=form.get(c.id+'-mode'),amount=+form.get(c.id+'-qty'),avgCurrency=form.get(c.id+'-avgCurrency'),avg=+form.get(c.id+'-avg');if(amount>0&&mode!=='qty'&&!freshness(c.id))throw Error(c.id+' 최신 시세를 수신한 후 금액으로 입력하세요.');if(((mode==='KRW'&&amount>0)||(avgCurrency==='KRW'&&avg>0))&&!(+form.get('fx')>0)&&!(state.fx&&Date.now()-state.fx.t<120000))throw Error('최신 환산 가격 수신을 기다리거나 수동 환산 가격을 입력하세요.');a.holdings[c.id]={qty:quantityFromInput(amount,mode,state.prices[c.id],fx),...manualCost(account.holdings[c.id],avg,avgCurrency,fx)};}a.cash=+form.get('cash');a.cashKRW=+form.get('cashKRW');a.fx=+form.get('fx');a.updatedAt=new Date().toISOString();validateAccount(a);if(!persist(a))throw Error(saveError);storageIssue=false;$('balance-dialog').close();render();toast('원화·USDT·코인 잔고를 저장했습니다.');}catch(err){$('balance-error').textContent=err.message;}};

function selectCoin(id){state.coin=id;renderCoins();renderChart();}for(const el of [$('coin-tabs'),$('coin-cards')])el.onclick=e=>{const b=e.target.closest('[data-coin]');if(b)selectCoin(b.dataset.coin);};
$('range-tabs').onclick=e=>{const b=e.target.closest('[data-days]');if(!b)return;state.days=+b.dataset.days;for(const x of e.currentTarget.children)x.classList.toggle('active',x===b);renderChart();};
$('show-band').onchange=e=>{state.bands=e.target.checked;renderChart();};$('chart-mode').onclick=()=>{state.candles=!state.candles;$('chart-mode').textContent=state.candles?'라인 차트':'캔들 차트';renderChart();};$('performance-range').onchange=()=>renderPerformance(true);$('refresh').onclick=()=>{loadMarket();sentiment();connect();};
$('privacy').onclick=()=>$('info-dialog').showModal();
$('export-account').onclick=()=>{const blob=new Blob([JSON.stringify(account,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='jace-crypto-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('잔고와 거래 기록이 포함된 백업 파일을 저장합니다.');};
$('import-account').onclick=()=>$('import-file').click();$('import-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>3000000)throw Error('3MB 이하의 백업 파일을 선택하세요.');const a=validateAccount(JSON.parse(await file.text()));if(!window.confirm('현재 잔고와 거래 기록을 선택한 백업으로 교체할까요? 기존 기록은 먼저 백업하는 것이 좋습니다.'))return;if(!persist(a))throw Error(saveError);storageIssue=false;render();renderJournal();toast('백업을 복원했습니다.');}catch(err){toast(err.message);}finally{e.target.value='';}};
function tradePreview(){const f=new FormData($('trade-form')),v=+f.get('qty'),price=+f.get('price'),q=f.get('inputMode')==='amount'?(price>0?v/price:0):v,currency=f.get('currency'),gross=q*price,fee=+f.get('fee');$('trade-conversion').textContent=`${fmt(q,8)} ${f.get('coin')} · ${f.get('side')==='buy'?'차감':'입금'} ${currency==='KRW'?won(gross+(f.get('side')==='buy'?fee:-fee)):fmt(gross+(f.get('side')==='buy'?fee:-fee))+' USDT'} · 환산 ${won(rate())}/USDT`;}
function fillTradePrice(){const f=$('trade-form').elements,price=state.prices[f.coin.value];f.price.value=finite(price)?+(price*(f.currency.value==='KRW'?rate()||0:1)).toFixed(f.currency.value==='KRW'?0:4):'';tradePreview();}
$('add-trade').onclick=()=>{$('trade-form').reset();const now=new Date();$('trade-form').elements.date.value=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16);$('trade-error').textContent='';fillTradePrice();$('trade-dialog').showModal();};
$('trade-form').oninput=tradePreview;$('trade-form').onchange=e=>{if(['currency','coin'].includes(e.target.name))fillTradePrice();else tradePreview();};
$('trade-form').onsubmit=e=>{e.preventDefault();try{const f=new FormData(e.target),dateValue=new Date(f.get('date')),currency=f.get('currency');if(dateValue.getTime()>Date.now()+60000)throw Error('미래 거래를 기록할 수 없습니다.');if(account.journal.length&&dateValue.getTime()<Date.parse(account.journal[0].date))throw Error('가장 최근 거래 이후의 체결을 순서대로 기록하세요.');if(currency==='KRW'&&!fxFresh())throw Error('원화 거래에는 최신 환산 가격 또는 수동 환산 가격이 필요합니다.');const price=+f.get('price'),qty=f.get('inputMode')==='amount'?+f.get('qty')/price:+f.get('qty');const a=applyTrade(account,{coin:f.get('coin'),side:f.get('side'),qty,price,fee:+f.get('fee'),currency,fx:rate(),date:dateValue.toISOString(),note:f.get('note')});if(!persist(a))throw Error(saveError);$('trade-dialog').close();render();renderJournal();toast(currency+' 거래를 기록하고 해당 현금 잔고에 반영했습니다.');}catch(err){$('trade-error').textContent=err.message;}};

document.querySelectorAll('.sidebar nav a').forEach(a=>a.onclick=()=>{document.querySelectorAll('.sidebar nav a').forEach(x=>x.classList.toggle('active',x===a));});
try{const cache=JSON.parse(localStorage.getItem(CACHE));if(cache&&cache.markets){for(const c of MARKET_COINS){const b=cache.markets[c.id];if(Array.isArray(b)&&b.length<=1000&&b.every(x=>Object.values(x).every(finite))){state.markets[c.id]=b;state.updated[c.id]=cache.updated?.[c.id]||0;if(finite(cache.prices?.[c.id]))state.prices[c.id]=cache.prices[c.id];state.tickers[c.id]=cache.tickers?.[c.id];state.tickerUpdated[c.id]=cache.tickerUpdated?.[c.id]||0;}}if(cache.fx&&finite(cache.fx.rate)&&cache.fx.rate>0&&finite(cache.fx.t))state.fx=cache.fx;state.cached=true;}}catch{}
recompute();renderAllocation();render();renderJournal();loadMarket();connect();connectFX();sentiment();
setInterval(async()=>{if(document.hidden)return;await Promise.allSettled([loadTickers(),loadFX()]);recompute();render();},30000);
setInterval(()=>{if(!document.hidden)loadMarket();},300000);
setInterval(renderStatus,15000);setInterval(sentiment,3600000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden){loadMarket();connect();}});
window.addEventListener('online',()=>{loadMarket();connect();});
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{account=validateAccount(JSON.parse(e.newValue));render();renderJournal();toast('다른 탭에서 변경한 잔고를 반영했습니다.');}catch{}}});

initReports(()=>({account,prices:state.prices,markets:state.markets,fx:rate(),fxSource:account.fx>0?'직접 입력':'업비트',fxIsFresh:fxFresh(),pricesFresh:Object.fromEntries(MARKET_COINS.map(c=>[c.id,freshness(c.id)]))}),{toast,storageKey:KEY,sandbox});
