import {finite} from './engine.mjs';
const fmt=x=>Math.abs(x)>=1000?new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(x):x.toFixed(Math.abs(x)<10?3:1);
export function spark(values,color){const a=values.filter(finite);if(a.length<2)return '';const lo=Math.min(...a),range=Math.max(...a)-lo||1;const points=a.map((v,i)=>`${i/(a.length-1)*84},${25-(v-lo)/range*21}`).join(' ');return `<svg class="spark" viewBox="0 0 84 29" aria-hidden="true"><polyline points="${points}" fill="none" stroke="${color}" stroke-width="1.5"/></svg>`;}
export class Chart{
 constructor(canvas,tooltip){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.tooltip=tooltip;this.options=null;this.hover=-1;this.observer=new ResizeObserver(()=>this.draw());this.observer.observe(canvas);if(tooltip){canvas.addEventListener('pointermove',e=>{const b=canvas.getBoundingClientRect();this.hover=Math.round((e.clientX-b.left-12)/(b.width-80)*((this.options?.bars.length||1)-1));this.draw();});canvas.addEventListener('pointerleave',()=>{this.hover=-1;tooltip.hidden=true;this.draw();});}}
 set(options){this.options=options;this.draw();}
 draw(){const {canvas,ctx}=this;const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;const dpr=window.devicePixelRatio||1,w=rect.width,h=rect.height;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);ctx.font='9px Manrope, sans-serif';ctx.lineJoin='round';const o=this.options;if(!o||o.bars.length<2)return;
 const b=o.bars,n=b.length,p={l:12,r:w-67,t:17,b:h-(o.volume?57:28)},x=i=>p.l+i/(n-1)*(p.r-p.l);const prices=[...b.flatMap(v=>o.candles?[v.l,v.h]:[v.c]),...(o.lines||[]).flatMap(l=>l.values.filter(finite))];let lo=Math.min(...prices),hi=Math.max(...prices);const span=hi-lo||Math.abs(hi)*.02||1;lo-=span*.09;hi+=span*.12;const y=v=>p.b-(v-lo)/(hi-lo)*(p.b-p.t);
 ctx.setLineDash([3,4]);for(let i=0;i<5;i++){const yy=p.t+(p.b-p.t)*i/4;ctx.strokeStyle='#303a3033';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(p.r,yy);ctx.stroke();ctx.fillStyle='#778476';ctx.fillText(fmt(hi-(hi-lo)*i/4),p.r+9,yy+3);}ctx.setLineDash([]);
 const line=(vals,color,width=1.4,dash=[])=>{ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();let started=false;for(let i=0;i<vals.length;i++){if(!finite(vals[i])){started=false;continue;}if(!started){ctx.moveTo(x(i),y(vals[i]));started=true;}else ctx.lineTo(x(i),y(vals[i]));}ctx.stroke();ctx.setLineDash([]);};
 if(o.band&&o.band.upper.every(finite)&&o.band.lower.every(finite)){ctx.beginPath();o.band.upper.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));for(let i=n-1;i>=0;i--)ctx.lineTo(x(i),y(o.band.lower[i]));ctx.closePath();ctx.fillStyle='#91a7ff0a';ctx.fill();line(o.band.upper,'#91a7ff55',.7);line(o.band.lower,'#91a7ff55',.7);}
 if(!o.candles){const grad=ctx.createLinearGradient(0,p.t,0,p.b);grad.addColorStop(0,'#d2f99a20');grad.addColorStop(1,'#d2f99a00');ctx.beginPath();ctx.moveTo(x(0),p.b);b.forEach((v,i)=>ctx.lineTo(x(i),y(v.c)));ctx.lineTo(x(n-1),p.b);ctx.closePath();ctx.fillStyle=grad;ctx.fill();line(b.map(v=>v.c),o.color||'#d2f99a',1.8);}else{const bw=Math.max(1,Math.min(8,(p.r-p.l)/n*.62));b.forEach((v,i)=>{ctx.strokeStyle=ctx.fillStyle=v.c>=v.o?'#9ccc9a':'#d98782';ctx.lineWidth=.8;ctx.beginPath();ctx.moveTo(x(i),y(v.h));ctx.lineTo(x(i),y(v.l));ctx.stroke();ctx.fillRect(x(i)-bw/2,Math.min(y(v.o),y(v.c)),bw,Math.max(1,Math.abs(y(v.c)-y(v.o))));});}
 for(const l of o.lines||[])line(l.values,l.color,l.width||1.3,l.dash||[]);
 if(o.volume){const max=Math.max(...b.map(v=>v.v))||1;const vw=Math.max(1,(p.r-p.l)/n*.65);b.forEach((v,i)=>{ctx.fillStyle=v.c>=v.o?'#52734677':'#81555266';const vh=v.v/max*23;ctx.fillRect(x(i)-vw/2,h-26-vh,vw,vh);});}
 for(let j=0;j<5;j++){const i=Math.round(j*(n-1)/4);const d=new Date(b[i].t),label=`${d.getUTCFullYear().toString().slice(2)}.${String(d.getUTCMonth()+1).padStart(2,'0')}.${String(d.getUTCDate()).padStart(2,'0')}`;ctx.fillStyle='#748271';ctx.textAlign=j===4?'right':j===0?'left':'center';ctx.fillText(label,x(i),h-8);}ctx.textAlign='left';
 const last=b.at(-1).c;ctx.fillStyle=o.color||'#d2f99a';ctx.fillRect(p.r+3,y(last)-9,61,18);ctx.fillStyle='#172415';ctx.font='bold 9px Manrope,sans-serif';ctx.fillText(fmt(last),p.r+7,y(last)+3);
 if(this.tooltip&&this.hover>=0&&this.hover<n){const i=this.hover,v=b[i];ctx.strokeStyle='#9dad8d88';ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(x(i),p.t);ctx.lineTo(x(i),h-27);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#d2f99a';ctx.beginPath();ctx.arc(x(i),y(v.c),3,0,Math.PI*2);ctx.fill();this.tooltip.hidden=false;this.tooltip.textContent=`${new Date(v.t).toISOString().slice(0,10)} · UTC\n종가 ${fmt(v.c)}${o.lines?.[0]&&finite(o.lines[0].values[i])?`\n${o.lines[0].label||'전략 SMA'} ${fmt(o.lines[0].values[i])}`:''}`;this.tooltip.style.left=x(i)>w*.55?'12px':'auto';this.tooltip.style.right=x(i)>w*.55?'auto':'76px';}
 }
}
