import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyAccount,MARKET_COINS,DAY} from './engine.mjs';
import {kstDay,validatePeriod,inPeriod,reportSnapshot,makeReport} from './report-core.mjs';
import worker,{ReportStore} from './kakao-worker/worker.mjs';

const key='test-only-admin-key-not-a-real-secret-1234';
const env={REPORT_ADMIN_KEY:key,KAKAO_REST_API_KEY:'test-kakao-app',DASHBOARD_URL:'https://example.com/crypto/'};
class Memory {map=new Map();async get(k){return structuredClone(this.map.get(k));}async put(k,v){this.map.set(k,structuredClone(v));}async delete(k){this.map.delete(k);}}
const setup=()=>{const storage=new Memory();return {storage,store:new ReportStore({storage},env)};};
const request=(path,body)=>new Request('https://worker.example'+path,{method:body===undefined?'GET':'POST',body:body===undefined?undefined:JSON.stringify(body)});
test('KST 날짜 경계, 시작/종료일 포함, 잘못된 날짜 거부',()=>{assert.equal(kstDay(Date.parse('2026-10-04T15:00:00Z')),'2026-10-05');const c={enabled:true,...validatePeriod('2026-10-05','2026-10-06')};assert.ok(inPeriod(c,Date.parse('2026-10-05T03:00Z')));assert.ok(inPeriod(c,Date.parse('2026-10-06T14:59Z')));assert.equal(inPeriod(c,Date.parse('2026-10-06T15:00Z')),false);assert.throws(()=>validatePeriod('2026-02-30','2026-03-01'));assert.throws(()=>validatePeriod('2026-10-07','2026-10-05'));});
test('보고서 스냅샷에서 메모/일지/추가 속성 제외',()=>{const a=emptyAccount();a.secret='private';a.snapshots=[{t:1,value:10}];a.holdings.BTC={qty:1,avg:100,avgKRW:130000,secret:'private'};const b=reportSnapshot(a);assert.equal(b.secret,undefined);assert.equal(b.holdings.BTC.secret,undefined);assert.deepEqual(b.snapshots,[]);assert.deepEqual(b.journal,[]);assert.equal(b.holdings.BTC.avgKRW,130000);});
test('요약은 원화 합계와 실제 원가 수익률, XRP 참고를 포함',()=>{const a=emptyAccount();a.holdings.BTC={qty:1,avg:100,avgKRW:130000};a.cashKRW=10000;a.cash=10;const text=makeReport({account:a,prices:{BTC:120},fx:1400,markets:{},now:Date.parse('2026-10-05T03:00Z')});assert.match(text,/192,000원/);assert.match(text,/38,000원/);assert.match(text,/XRP\(참고\) 235일/);assert.ok(text.length<=1000);const missing=makeReport({account:a,prices:{},fx:1400,markets:{}});assert.match(missing,/총자산 확인 중/);assert.match(missing,/평가 확인 중/);});
test('관리 키 및 허용 Origin 없이 제어 불가, 외부 tick 차단',async()=>{const fakeEnv={...env,REPORT:{idFromName:()=>1,get:()=>({fetch:()=>Response.json({ok:true})})}};assert.equal((await worker.fetch(new Request('https://worker.example/status'),fakeEnv)).status,401);assert.equal((await worker.fetch(new Request('https://worker.example/status',{headers:{Authorization:'Bearer '+key,Origin:'https://evil.example'}}),fakeEnv)).status,403);assert.equal((await worker.fetch(new Request('https://worker.example/tick',{headers:{Authorization:'Bearer '+key}}),fakeEnv)).status,404);const r=await worker.fetch(new Request('https://worker.example/status',{headers:{Authorization:'Bearer '+key,Origin:'https://example.com'}}),fakeEnv);assert.equal(r.status,200);assert.equal(r.headers.get('Access-Control-Allow-Origin'),'https://example.com');});
test('카카오 미연결이면 시작 거부, 연결 후 시작·동기화·중지',async()=>{const {store,storage}=setup(),day=kstDay();const body={start:day,end:day,account:emptyAccount()};assert.equal((await store.fetch(request('/report/start',body))).status,400);await storage.put('tokens',{refresh_token:'test'});assert.equal((await store.fetch(request('/report/start',body))).status,200);body.account.cash=123;await store.fetch(request('/report/sync',{account:body.account}));assert.equal((await storage.get('config')).account.cash,123);await store.fetch(request('/report/stop',{}));assert.equal((await store.status()).enabled,false);});
test('OAuth 잘못된 state / 만료 state는 토큰 교환 전에 차단',async()=>{const {store,storage}=setup();await storage.put('oauth',{state:'known',expires:Date.now()+10000});assert.equal((await store.fetch(request('/oauth/callback?state=bad&code=test'))).status,400);assert.equal(await storage.get('tokens'),undefined);});
function marketMock(now,{ambiguous=false,stale=false}={}){let sends=0,refreshes=0;return {get sends(){return sends;},get refreshes(){return refreshes;},fetch:async(url,opts)=>{url=String(url);if(url.includes('/klines?')){const start=Math.floor(now/DAY)*DAY-299*DAY;return Response.json(Array.from({length:300},(_,i)=>[start+i*DAY,100,101,99,100,1000,start+(i+1)*DAY-1]));}if(url.includes('/ticker/24hr'))return Response.json({lastPrice:'100',closeTime:stale?now-300000:now});if(url.includes('api.upbit.com'))return Response.json([{trade_price:1400,timestamp:now}]);if(url.includes('/oauth/token')){refreshes++;return Response.json({access_token:'new-access',refresh_token:'rotated-refresh',expires_in:3600});}if(url.includes('/memo/default/send')){sends++;assert.match(opts.headers.Authorization,/Bearer/);const text=JSON.parse(opts.body.get('template_object')).text;assert.ok(text.length<=1000);if(ambiguous)throw Error('network timeout');return Response.json({result_code:0});}throw Error('Unexpected test URL');}};}
test('정상 예약 발송, 토큰 회전 저장, 같은 날 중복 호출 차단',async t=>{const {store,storage}=setup(),now=Date.now(),day=kstDay(now),mock=marketMock(now);t.mock.method(globalThis,'fetch',mock.fetch);await storage.put('config',{enabled:true,start:day,end:day,account:emptyAccount()});await storage.put('tokens',{access_token:'expired',refresh_token:'old',expires:0});const a=await store.sendDaily(now),b=await store.sendDaily(now);assert.equal(a.state,'sent');assert.ok(b.skipped);assert.equal(mock.sends,1);assert.equal(mock.refreshes,1);assert.equal((await storage.get('tokens')).refresh_token,'rotated-refresh');});
test('발송 응답 불명확 시 같은 날 재발송하지 않음',async t=>{const {store,storage}=setup(),now=Date.now(),day=kstDay(now),mock=marketMock(now,{ambiguous:true});t.mock.method(globalThis,'fetch',mock.fetch);await storage.put('config',{enabled:true,start:day,end:day,account:emptyAccount()});await storage.put('tokens',{access_token:'valid',refresh_token:'refresh',expires:now+3600000});assert.equal((await store.sendDaily(now)).state,'error');await store.sendDaily(now);assert.equal(mock.sends,1);});
test('시세 지연, 중지, 종료일 경과 시 메시지 전송 없음',async t=>{const {store,storage}=setup(),now=Date.now(),day=kstDay(now),mock=marketMock(now,{stale:true});t.mock.method(globalThis,'fetch',mock.fetch);const config={enabled:true,start:day,end:day,account:emptyAccount()};await storage.put('config',config);assert.equal((await store.sendDaily(now)).state,'error');await storage.put('config',{...config,enabled:false});assert.ok((await store.sendDaily(now)).skipped);await storage.put('config',{...config,start:'2020-01-01',end:'2020-01-02'});assert.ok((await store.sendDaily(now)).skipped);assert.equal((await storage.get('config')).enabled,false);assert.equal(mock.sends,0);});

test('보고서 스냅샷과 요약에 XRP 원가/수량/손익 포함, 구버전 호환',()=>{const a=emptyAccount();a.holdings.XRP={qty:100,avg:1,avgKRW:1300};const b=reportSnapshot(a);assert.deepEqual(b.holdings.XRP,a.holdings.XRP);const text=makeReport({account:b,prices:{XRP:2},markets:{},fx:1400});assert.match(text,/총자산 280,000원/);assert.match(text,/평가손익 150,000원/);assert.match(text,/XRP 100개 · 평가 280,000원/);assert.match(text,/목표 배분 제외/);delete a.holdings.XRP;assert.deepEqual(reportSnapshot(a).holdings.XRP,{qty:0,avg:0,avgKRW:null});});
